### ISSUE TITLE
Comet submit

### ISSUE THREAD

**Issue by danidewitt** [LaunchAcademy/comet#19]
I have tried comet submit in the comet directory and the challenge directory. I also tried gem installing comet again. I get "Not a challenge directory" in all of these cases. 
![ziy2wlzywkqoc12cvc0he5abxeknj5hztdrvgymhezu](https://f.cloud.github.com/assets/3790037/2253850/62e5046e-9dc7-11e3-8397-7eff37e8e2eb.png)

**Comment by atsheehan** [comment]
Should be fixed in comet 0.0.7. Try `gem update comet` and resubmitting the kata.
