### ISSUE TITLE
Comet does not recognize challenge directory

### ISSUE THREAD

**Issue by gsheppard** [LaunchAcademy/comet#20]
Version: 0.0.6
`comet list` and `comet fetch` work for Challenge #20 (Regex drills, which saves to comet/drills), but `comet submit` returns "Not a challenge directory."

I downloaded it another time and tried to submit it again but got the same error.

**Comment by atsheehan** [comment]
Should be fixed in comet 0.0.7. Try `gem update comet` and resubmitting the kata.
