### ISSUE TITLE
Comet 22 does not have minitest

### ISSUE THREAD

**Issue by gsheppard** [LaunchAcademy/comet#22]
Comet 22 (Classes: Student Grades) does not have

``` ruby
require 'minitest/spec'
require 'minitest/autorun'
```

included in the test/sudent_grades.rb file.

**Comment by gsheppard** [comment]
After running minitest I realize

``` ruby
require 'rspec'
```

may be the goal. Oops.

**Comment by atsheehan** [comment]
You can run the `comet test` command within the kata directory and it will figure out what the correct test runner is.
